WB=colorRampPalette(c("white", "black"),space = "Lab")
WGB=colorRampPalette(c("white","green","blue"),space = "Lab")
WBR=colorRampPalette(c("white","blue","red"),space = "Lab")
WBlaR=colorRampPalette(c("white","black","red"),space = "Lab")
VOLC=colorRampPalette(c("gray80","gray50","black","red"),space = "Lab")
DYN=colorRampPalette(c("darkblue","blue","green","white","yellow","red","darkred"),space = "Lab")
RBW=colorRampPalette(c("red","blue","white"),space = "Lab")
RBlW=colorRampPalette(c("red","black","white"),space = "Lab")
WRB=colorRampPalette(c("white", "red", "black"),space = "Lab")
POURC=colorRampPalette(c("white","green","red", "yellow"),space = "Lab")
DBR=colorRampPalette(c("navyblue","blue","white", "red","darkred"),space = "Lab")
BR=colorRampPalette(c("blue","white", "red"),space = "Lab")
BYR=colorRampPalette(c("blue","yellow", "red"),space = "Lab")
pos=colorRampPalette(c("white", "yellow","red", "black"),space = "Lab")
neg=colorRampPalette(c("black","blue","green","white"),space = "Lab")
SLP=colorRampPalette(c("navyblue","blue","skyblue","white","yellow","orange","red"),space = "Lab")
light_centered=colorRampPalette(c("skyblue","blue", "white","red","yellow"),space = "Lab")
PRECIP=colorRampPalette(c("brown","orange","white","blue","darkblue"),space = "Lab")
BlueDarkRed=colorRampPalette(c("navyblue","blue","white","red","darkred"),space = "Lab")
#col10=rainbow(length(zlev)-1,start=0,end=2/6)
RMSEPAL=colorRampPalette(c("darkred","red","orange","yellow","green","white"),space = "Lab")
RMSEPAL2=colorRampPalette(c("darkred","red","orange","yellow","green","black",rep("white",5)),space = "Lab")
RMSEPAL3=colorRampPalette(c("red","purple","blue","lightblue","black",rep("white",4)),space = "Lab")
RMSEPAL3inv=colorRampPalette(c("white","darkturquoise","black","yellow","red"),space = "Lab")
VARPAL=colorRampPalette(c("white","darkturquoise","green","yellow","red"),space = "Lab")
CORREL=colorRampPalette(c("navyblue","blue","skyblue","white","yellow","red","darkred"),space = "Lab")
CORREL2=colorRampPalette(c("darkturquoise","navyblue","blue","skyblue","white","yellow","red","darkred","deeppink"),space = "Lab")
SALT=colorRampPalette(c("navyblue","blue","skyblue","green","yellow","red","darkred"),space = "Lab")
RedGreen=colorRampPalette(c("green3","white","firebrick2"),space = "Lab")

